apiVersion: v1
kind: Pod
metadata:
  name: blue-app
  labels:
    app: blue-app
spec:
  serviceAccountName: blue-app-ksa
  containers:
  - name: blue-app
    image: guptajitech/python-quote-app:blue
    ports:
      - containerPort: 5000
    envFrom:
      - configMapRef:
          name: blue-app-cm
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"