apiVersion: v1
kind: Pod
metadata:
  name: green-app
  labels:
    app: green-app
spec:
  serviceAccountName: green-app-ksa
  containers:
  - name: green-app
    image: guptajitech/python-quote-app:green
    ports:
      - containerPort: 5000
    envFrom:
      - configMapRef:
          name: green-app-cm
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"